sudo: required
dist: trusty
language: node_js
node_js:
- "6"
cache:
  directories:
  - web-src/node_modules
addons:
  chrome: stable
before_install:
- sudo apt-get -y install python3-pip
install:
- sudo pip3 install -r requirements.txt
- sudo pip3 install ldap3
- cd web-src
- npm install
- cd ..
before_script:
- cd src
  python3 -m unittest discover -s tests -p "*.py"
- cd ../web-src
- npm run test
- cd ..
script:
- python3 tools/build.py