if: tag IS blank
sudo: required
dist: xenial
language: node_js
node_js:
- '6'
cache:
  directories:
  - web-src/node_modules
addons:
  chrome: stable
env:
  global:
  - OWNER=${TRAVIS_REPO_SLUG%/*}
  - secure: "GtWCiMPNz3MDDTvXqaVsgZBvlxYRZuTY6sUEhWTL37zJZHgRLlxTCTD27hHZp2P4B6G6KGV/0iEvMYxqzo6jMrzcEnt7TlGetteqI18dhV1dIQGH6uy8Y/PktkK2g2FuJeGV3FRK4+a21v6zzSuUaFa26k97mPapa4LS83XXj7rc13ll23HhhtObVF/a1n3U0Xwe4FkdoxbKlecJUnNujESxFk4xQl4N1tFv15fldDlFq0XWs26eEp3LU/n7wkMzbg9WEqPvDeaYlvir9VpvcYWpVvf8Uz+wpvW1jnE2R6bK1TDv5BNzQwbf2JtN284yZ8I1nwZtOJkc1RUr5wUFxCD0p8tc30sAlKemI385v2t1ccoBYMwH8LHFIUoSXoolHZBsnZeADqpo3a0d8hVFWv4AcxC27Q6SfMCltl0+ogAoQ7wVfkRT++044p415Ar4raEqIkqTm64FaRNMS0v2y5mS2634PMSGMRnK+NBrWz1yFKxsiuPKypIWygtrJ4pyiL2yPBZupnCluEgqva3q6AmMDlNuSUmcTEnCRGB01U2if6/oSEgISH1VK2lsRSxuoG5dFFuezwv90YENh/7pw0/hgge7EOse6OzDsU3uNRWcTuXF7eEBhjM1wBHWHlaAwV9vfHMZX4sHWP4R4CZhPjVEPRz6HPEg1tFCs2EvkuI="
before_install:
- sudo apt-get -y install python3-pip python3-setuptools
install:
- sudo pip3 install -r requirements.txt
- sudo pip3 install ldap3
- sudo pip3 install pyasn1 --upgrade
- cd web-src
- npm install
- cd ..
before_script:
- cd src
- python3 -m unittest discover -s tests -p "*.py"
- cd ../web-src
- npm run test
- cd ..
script:
- python3 tools/build.py
before_deploy:
- git config --local user.name 'bugy'
- git config --local user.email 'buggygm@gmail.com'
- git tag -f 'dev'
- git remote add gh https://${OWNER}:${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
- git push -f gh dev
- git remote remove gh
deploy:
  provider: releases
  name: dev
  api_key: $GITHUB_TOKEN
  file: build/script-server.zip
  prerelease: true
  overwrite: true
  skip_cleanup: true
  on:
    branch: master